### ISSUE TITLE
やること - v0.1.0

### ISSUE THREAD

**Issue by kawasin73** [kawasin73/twilter#4]
とりあえず、1人で使えるところまで実装する。

### やること一覧

- [x] 利用する API の調査とまとめ #3 
- [x] Stream API の検討 #9
- [x] Go での Twitter クライアントライブラリの選定 #2 
- [x] 実装
- [x] AccessToken と AccessTokenSecret を取得するための簡易アプリ~~の作成~~ #7 
- [x] Docker イメージの準備 #14 
- [x] 自宅 kubernetes へデプロイ
- [x] README の作成

### 必要な機能

- [x] あるユーザーのツイート一覧の取得
- [x] ツイートのフィルタリング
- [x] リツイートの投稿
- [x] リツイート済みのツイートのリツイート解除
- [x] ツイート監視のスケジューリング
- [x] 各ユーザーのどのツイートから監視するかを指定する
- [x] どのツイートまで監視したかを永続化する #12 
- [x] コマンドラインで起動 #10 
- [x] Rate Limit の再送処理 #6 
- [x] フィルターの充実 #5 
  - [x] RT
  - [x] Not RT
  - [x] And
  - [x] Or
